<?php

namespace App\Controller;

use App\Entity\Hook;
use App\Repository\HookRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/hook')]
class HookController extends MasterController
{
    public function __construct(ManagerRegistry $registry)
    {
        $this->setObject(new Hook());
        $this->setObjectRepository(new HookRepository($registry));
        parent::__construct($registry);
    }

    #[Route('/', name: 'app_hook_index', methods: ['GET'])]
    public function index(): Response
    {
        return parent::index();
    }

    #[Route('/new', name: 'app_hook_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        return parent::new($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}', name: 'app_hook_show', methods: ['GET'])]
    public function show(Request $request): Response
    {
        return parent::show($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}/edit', name: 'app_hook_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request,): Response
    {
        return parent::edit($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}', name: 'app_hook_delete', methods: ['POST'])]
    public function delete(Request $request): Response
    {
        return parent::delete($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}/enable', name: 'app_hook_enable', methods: ['GET', 'POST'])]
    public function enable(Request $request): Response
    {
        return parent::enable($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}/disable', name: 'app_hook_disable', methods: ['GET', 'POST'])]
    public function disable(Request $request): Response
    {
        return parent::disable($request); // TODO: Change the autogenerated stub
    }

}
