<?php

namespace App\Controller;

use App\Entity\PriceStatus;
use App\Repository\PriceStatusRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/price_status')]
class PriceStatusController extends MasterController
{
    public function __construct(ManagerRegistry $registry)
    {
        $this->setObject(new PriceStatus());
        $this->setObjectRepository(new PriceStatusRepository($registry));
        parent::__construct($registry);
    }

    #[Route('/', name: 'app_price_status_index', methods: ['GET'])]
    public function index(): Response
    {
        return parent::index();
    }

    #[Route('/new', name: 'app_price_status_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        return parent::new($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}', name: 'app_price_status_show', methods: ['GET'])]
    public function show(Request $request): Response
    {
        return parent::show($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}/edit', name: 'app_price_status_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request,): Response
    {
        return parent::edit($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}', name: 'app_price_status_delete', methods: ['POST'])]
    public function delete(Request $request): Response
    {
        return parent::delete($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}/enable', name: 'app_price_status_enable', methods: ['GET', 'POST'])]
    public function enable(Request $request): Response
    {
        return parent::enable($request); // TODO: Change the autogenerated stub
    }

    #[Route('/{id}/disable', name: 'app_price_status_disable', methods: ['GET', 'POST'])]
    public function disable(Request $request): Response
    {
        return parent::disable($request); // TODO: Change the autogenerated stub
    }

}
